# Generated by Django 4.1.5 on 2023-01-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_crosstable_owner_alter_crosstable_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crosstable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='crosstable',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='crosstable',
            unique_together={('word', 'meaning', 'username')},
        ),
        migrations.RemoveField(
            model_name='crosstable',
            name='owner',
        ),
    ]
