# Generated by Django 4.1.5 on 2023-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_crosstable_unique_together_crosstable_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosstable',
            name='username',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
