# Generated by Django 4.1.5 on 2023-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_crosstable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosstable',
            name='username',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
